import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { ReactQueryProvider } from './ReactQueryProvider'
import { ReactProvider } from './redux-toolkit/provider'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
  weight: '100',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'OnlineStore',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <ReactProvider>
            {children}
            <ReactQueryDevtools initialIsOpen={false} />
          </ReactProvider>
        </body>
      </html>
    </ReactQueryProvider>
  )
}
